from selenium.webdriver.common.by import By

CustomHomepage = (By.LINK_TEXT, '自定义首页')
HSE = (By.LINK_TEXT, 'HSE')
RunHuaGuanLi = (By.LINK_TEXT, '润滑管理')
GongYiGuanLi = (By.LINK_TEXT, '工艺管理')
JiDianGuanLi = (By.LINK_TEXT, '机电管理')
XinXiKu = (By.LINK_TEXT, '信息库')
TrainingSystem = (By.LINK_TEXT, '人员培训系统')
CoreDataSystem = (By.LINK_TEXT, '关键数据系统')
EquipAnormalyManagment = (By.LINK_TEXT, '设备仪表异常管理')
OrderSystem = (By.LINK_TEXT, '作业单系统')
EquipDailyManagment = (By.LINK_TEXT, '设备仪表日常管理')
CylinderGuanLi = (By.LINK_TEXT, '钢瓶管理')
Community = (By.LINK_TEXT, '交流社区')
ReportAccident = (By.LINK_TEXT, '事故上报')
ProfesssorSystem = (By.LINK_TEXT, '专家系统')
SystemGuanLi = (By.LINK_TEXT, '系统管理')
SheBeiJianKong = (By.LINK_TEXT, '设备监控')
Workbill_Config = (By.LINK_TEXT, '作业票配置')
Examination = (By.LINK_TEXT, '检验检测')
MyWorkPanel = (By.XPATH, '//h1[text()="我的工作面板"]')

Notice = (By.XPATH, '//a[@href="/Web/Common/Notice"]')